create table if not exists public.guidance_leads (
  id bigint generated by default as identity primary key,
  full_name text not null,
  phone text not null,
  current_stage text not null,
  message text,
  source_page text,
  page_url text,
  created_at timestamptz not null default now()
);

alter table public.guidance_leads enable row level security;

drop policy if exists "Allow public lead inserts" on public.guidance_leads;

create policy "Allow public lead inserts"
on public.guidance_leads
for insert
to anon
with check (true);

create table if not exists public.accommodation_enquiries (
  id bigint generated by default as identity primary key,
  name text not null,
  gender text not null,
  phone_number text not null,
  college_name text not null,
  campus text,
  monthly_budget text not null,
  additional_requirements text,
  created_at timestamptz not null default now()
);

alter table public.accommodation_enquiries
add column if not exists campus text;

alter table public.accommodation_enquiries enable row level security;

drop policy if exists "Allow public accommodation enquiry inserts" on public.accommodation_enquiries;

create policy "Allow public accommodation enquiry inserts"
on public.accommodation_enquiries
for insert
to public
with check (true);

grant insert on public.accommodation_enquiries to anon, authenticated;
grant usage, select on sequence public.accommodation_enquiries_id_seq to anon, authenticated;
