create table if not exists public.guidance_leads (
  id bigint generated by default as identity primary key,
  full_name text not null,
  phone text not null,
  current_stage text not null,
  message text,
  source_page text,
  page_url text,
  created_at timestamptz not null default now()
);

alter table public.guidance_leads enable row level security;

drop policy if exists "Allow public lead inserts" on public.guidance_leads;

create policy "Allow public lead inserts"
on public.guidance_leads
for insert
to anon
with check (true);
